acc_suggest_pro: []
anchortype: 2
angle: 360
batchsize: 64
cell_stride: 1
cellsize: 16
expand_size:
- 1
- 1
f1_suggest_pro:
- 0
gpus: '2'
ignore_size:
- 0
- 0
imagesize:
- 512
- 512
labelsfilename: ''
lablelist: []
maxiter: 120000
modeldcfgname: yolov4-tiny-3l.cfg
modelname: '20081209'
path_prefix: data/images/
pixelareafpthresh:
- 1.52e-05
- 1.52e-07
pretraincfgname: ''
pretrainweight: ''
random: 1
recall_suggest_pro: []
resizearrange:
- 0.3
- 1.2
rmgeneratedata: 1 # 0是删除 1：不删   是否删除训练生成的临时数据
scale: 1
singletrain: []
split_ratio: 0.95
subdivisionssize: 8
sum_suggest_pro: []
traintype: 0
trainwithnolabelpic: 100000
otherlabeltraintype: 1 # 0不开启 1开启， 可能存在其他类型 非当前标签图片训练方式
recalldatum: 2
mergeTrainSymbol: 0 # 是否开启多标签单模型训练 0 关闭 1 开启
